server:
  port: 8082

spring:
  application:
    name: note-service
  cloud:
    nacos:
      config:
        server-addr: nacos.jktu.cc:8848
      discovery:
        server-addr: nacos.jktu.cc:8848
  config:
    import:
      - nacos:note-service.yml
      - nacos:mybatis-plus.yml
      - nacos:spring-mvc.yml
  devtools:
    livereload:
      port: 10002
